### ISSUE TITLE
Remove lorem ipsum and other placeholders

### ISSUE THREAD

**Issue by trstephen** [trstephen/seng462-test#2]
Write some actual copy, i guess?

#### TODO
- [ ] Remove FAQs
- [ ] Remove contact page?
- [ ] Lorem ipsum blog posts
- [ ] Give names to other (blank) projects
